FROM docker.elastic.co/kibana/kibana:8.0.0

ARG ELK_VERSION

# https://www.docker.elastic.co/
#FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
