root@GlobalPrimeLogservice:~/docker-elk/extensions/curator# cat config/curator.yml
# Curator configuration
# https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html

client:
  hosts:
    - elasticsearch
  port: 9200
  http_auth: 'elastic:changeme'

logging:
  loglevel: INFO
  logformat: default
